CREATE TABLE customers(
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  first_name VARCHAR (100) NOT NULL,
  last_name VARCHAR (100) NOT NULL,
  email VARCHAR (255) NOT NULL UNIQUE,
  phone VARCHAR (100),
  city VARCHAR (100),
  country VARCHAR (100),
  date_of_birth DATE, 
  gender VARCHAR(50),
  occupation VARCHAR(255),
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
  );

  CREATE TABLE products(
  product_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_name VARCHAR(255) NOT NULL,
  min_target_age INT NOT NULL,
  max_target_age INT NOT NULL,
  product_description TEXT NOT NULL,
  product_category VARCHAR(100) NOT NULL,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
  );

 CREATE TABLE colors(
  color_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  color_name VARCHAR(100) NOT NULL UNIQUE,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
  );


 CREATE TABLE product_variants(
 variant_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 product_id INT REFERENCES products(product_id),
 color_id INT REFERENCES colors(color_id),
 size VARCHAR(100),
 material VARCHAR(255),
 current_price DECIMAL(10, 2) NOT NULL,
 purchase_price DECIMAL(10, 2) NOT NULL,
 stock INT NOT NULL,
 image_url VARCHAR(255),
 created_at timestamp DEFAULT CURRENT_TIMESTAMP
 );

  CREATE TABLE seasons(
  season_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  season_name VARCHAR(100) NOT NULL UNIQUE,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
  );

  CREATE TABLE product_seasons(
  season_id INT NOT NULL REFERENCES seasons(season_id),
  product_id INT NOT NULL REFERENCES products(product_id),
    PRIMARY KEY (season_id, product_id)
  );


  CREATE TABLE orders(
  order_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  customer_id INT REFERENCES customers(id),
  order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(50) NOT NULL,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
  );

  CREATE TABLE order_items(
  order_id INT REFERENCES orders(order_id),
  variant_id INT REFERENCES product_variants(variant_id),
  quantity INT NOT NULL,
  sold_price DECIMAL(10, 2) NOT NULL,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (order_id, variant_id)
  );