CREATE TABLE customers (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(100),
    city VARCHAR(100),
    country VARCHAR(100),
    date_of_birth DATE,
    gender VARCHAR(50),
    occupation VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE products (
    product_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_name VARCHAR(255) NOT NULL,
    min_target_age INT NOT NULL,
    max_target_age INT NOT NULL,
    product_description TEXT NOT NULL,
    product_category VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE colors (
    color_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    color_name VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE product_variants (
    variant_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INT REFERENCES products(product_id),
    color_id INT REFERENCES colors(color_id),
    size VARCHAR(100) NOT NULL,
    material VARCHAR(255),
    current_price DECIMAL(10, 2) NOT NULL,
    purchase_price DECIMAL(10, 2) NOT NULL,
    stock INT NOT NULL,
    image_url VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    UNIQUE (product_id, color_id, size)
);


CREATE TABLE seasons (
    season_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    season_name VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE product_seasons (
    season_id INT NOT NULL REFERENCES seasons(season_id),
    product_id INT NOT NULL REFERENCES products(product_id),

    PRIMARY KEY (season_id, product_id)
);


-- Doit être créée avant orders,
-- car orders possède une clé étrangère vers cette table.
CREATE TABLE marketing_campaigns (
    campaign_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    campaign_name VARCHAR(100) NOT NULL,
    platform VARCHAR(100) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    budget DECIMAL(10, 2) NOT NULL,
    amount_spent DECIMAL(10, 2) DEFAULT 0,
    likes INT DEFAULT 0,
    shares INT DEFAULT 0,
    impressions INT DEFAULT 0,
    clicks INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE orders (
    order_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_id INT REFERENCES customers(id),
    campaign_id INT REFERENCES marketing_campaigns(campaign_id),
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE order_items (
    order_id INT REFERENCES orders(order_id),
    variant_id INT REFERENCES product_variants(variant_id),
    quantity INT NOT NULL,
    sold_price DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (order_id, variant_id)
);


CREATE TABLE shipping (
    shipping_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id INT UNIQUE REFERENCES orders(order_id),
    shipping_address VARCHAR(255) NOT NULL,
    shipping_city VARCHAR(100) NOT NULL,
    shipping_country VARCHAR(100) NOT NULL,
    shipping_status VARCHAR(50) NOT NULL,

    shipping_date TIMESTAMP,
    expected_delivery_date TIMESTAMP,
    delivery_date TIMESTAMP,

    shipping_transport_method VARCHAR(100) NOT NULL,
    shipping_cost DECIMAL(10, 2) NOT NULL,
    transport_company VARCHAR(100) NOT NULL,
    transport_tracking_number VARCHAR(100) NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE payments (
    payment_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id INT UNIQUE REFERENCES orders(order_id),
    payment_method VARCHAR(100) NOT NULL,
    payment_status VARCHAR(50) NOT NULL,
    payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    amount DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE website_traffic (
    traffic_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    campaign_id INT REFERENCES marketing_campaigns(campaign_id),
    traffic_date DATE NOT NULL,
    visitors INT DEFAULT 0,
    sessions INT DEFAULT 0,
    page_views INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE promotions (
    promotion_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    promotion_name VARCHAR(100) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    discount_percentage DECIMAL(5, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE product_promotions (
    promotion_id INT NOT NULL REFERENCES promotions(promotion_id),
    product_id INT NOT NULL REFERENCES products(product_id),

    PRIMARY KEY (promotion_id, product_id)
);


CREATE TABLE admin_users (
    admin_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    role VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);