CREATE TABLE marketing_campaigns (
    campaign_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    campaign_name VARCHAR(100) NOT NULL,
    platform VARCHAR(100) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    budget DECIMAL(10, 2) NOT NULL,
    amount_spent     DECIMAL(10, 2) DEFAULT 0,
    likes INT DEFAULT 0,
    shares INT DEFAULT 0,
    impressions INT DEFAULT 0,
    clicks INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE website_traffic (
    traffic_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    campaign_id INT REFERENCES marketing_campaigns(campaign_id),
    traffic_date DATE NOT NULL,
    visitors INT DEFAULT 0,
    sessions INT DEFAULT 0,
    page_views INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE promotions (
    promotion_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    promotion_name VARCHAR(100) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    discount_percentage DECIMAL(5, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE product_promotions (
    promotion_id INT NOT NULL REFERENCES promotions(promotion_id),
    product_id INT NOT NULL REFERENCES products(product_id),

    PRIMARY KEY (promotion_id, product_id)
);